global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
remote_write:
- url: https://prometheus-us-central1.grafana.net/api/prom/push
  basic_auth:
    username: 827289
    password: eyJrIjoiMjNkNzc0MGNlNzhjM2U3MTAyOTE1MzY1MmNlYzYwNDE2NDcxYjk3NCIsIm4iOiJwcm9tLXB1Ymxpc2hlciIsImlkIjo4MTYyNzF9
alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: []
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - localhost:9090
    - host.docker.internal:8000
