apiVersion: batch/v1
kind: CronJob
metadata:
  name: predict-sentiment
spec:
  schedule: "* */12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: predict-sentiment
            image: afif2100/sentiment-batch-job:latest
            imagePullPolicy: IfNotPresent
            env:
            - name: PG_HOST
              value: "kube-db-postgresql.default.svc.cluster.local"
            - name: PG_DATABASE
              value: "playstore"
            - name: PG_PASS
              valueFrom:
                secretKeyRef:
                  name: kube-db-postgresql
                  key: postgres-password
          restartPolicy: Never # OnFailure