# FROM python:3.7.12-slim-buster
FROM python:3.10.7-slim-buster

COPY mlflow-storage-gcs.json ./gcs.json
ENV GOOGLE_APPLICATION_CREDENTIALS=gcs.json

RUN pip install --upgrade pip
RUN pip install boto3 psycopg2-binary
RUN pip install google-cloud-storage
RUN pip install mlflow==2.0.1

ENTRYPOINT mlflow server --backend-store-uri $BACKEND_STORE_URI --default-artifact-root $ARTIFACT_STORE --host 0.0.0.0