
name: Python package

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3
    - id: auth
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: 'projects/110817751945/locations/global/workloadIdentityPools/github-identity-pool/providers/ds-github-identity-pool-provider'
        service_account: 'mlflow-user@hvzn-development.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: 'Use gsutil LS'
      run: ' gsutil ls gs://hvzn-gcs-us-1'

    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda activate test && python -m pip install --upgrade pip
        pip install coverage pytest setuptools wheel
        pip install gcsfs numpy pandas
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with pytest
      shell: bash -l {0}
      run: |
        conda activate test && coverage run --source=hvzn -m pytest -o log_cli=true -v tests
        coverage report -m
