
name: Python package

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3
    - id: auth
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: 'projects/110817751945/locations/global/workloadIdentityPools/github-identity-pool/providers/ds-github-identity-pool-provider'
        service_account: 'mlflow-user@hvzn-development.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: 'Use gsutil LS'
      run: ' gsutil ls gs://hvzn-gcs-us-1'
