
name: Python package

on: ['pull_requests']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6']

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda activate test && python -m pip install --upgrade pip
        pip install setuptools wheel
        pip install pytest pytest-cov
        pip install gcsfs numpy pandas
        pip install gcp-storage-emulator

    - name: Test with pytest
      shell: bash -l {0}
      run: |
        conda activate test && pytest
